extends Node

signal attackDamageDealt
signal attackDamageRecieve
signal enemyTargeted
signal selectingEnemies
signal choosingActions
signal choseAction
signal characterActivated
signal characterWaiting
