extends Node

signal enemiesSpawned
signal charactersSpawned

signal battlerActivated
signal characterActivated
signal characterWaiting
signal choosingActions
signal choseAction
signal enemyTargeted
signal selectingEnemies

signal attackDamageDealt
signal attackDamageRecieve
signal statsChanged

signal battlerFinishedTurn
